; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_touch]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

; ESP-IDF 相关配置
board_build.flash_mode = qio
board_build.f_flash = 80000000L

; 串口监视器
monitor_speed = 115200

; 上传端口（根据实际端口修改）
upload_port = COM8
monitor_port = COM8

; 配置触摸点数
build_flags =
    -D CONFIG_ESP_LCD_TOUCH_MAX_POINTS=5

; 帧数据分区 + Flash 16MB
board_build.partitions = partitions.csv
board_build.flash_size = 16MB
